### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by bertomartin** [bertomartin/mongoblog#4]
http://stackoverflow.com/questions/4976567/get-a-list-of-all-unique-tags-in-mongodb/4977057#4977057

**Comment by wmorris75** [comment]
The following has been done: 
          -Get all the unique tags and display them on the article#index page
          -Get articles by a single tag

**Comment by wmorris75** [comment]
The following has been done: 
-Get all the unique tags and display them on the article#index page
-Get articles by a single tag
