### ISSUE TITLE
Contact capability

### ISSUE THREAD

**Issue by bertomartin** [bertomartin/mongoblog#6]
Add a contact form and associated model

**Comment by wmorris75** [comment]
Contact form has been added along with the ability to save the user's information to a mailing list. Need to confirm whether requirements are met.

**Comment by bertomartin** [comment]
@wmorris75 great, I'll take a look!

**Comment by wmorris75** [comment]
Need to scope requirements for how emails will be sent.  For example, Set up a page where user is able to enter into form a single email, list of emails or all emails and text area for content which will be emailed to all user subscriber via mail api.
